
services:
  rdgen:
    build: .
    container_name: rdgen-sajat-szerver
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      # (Opcionális) Kivezetjük a fájlokat, hogy a konténer törlése után is meglegyenek a gépeden
      - ./generated_exe:/app/exe
      - ./generated_png:/app/png