name: Custom Windows Client Generator
run-name: Custom Windows Client Generator
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'RustDesk version'
        required: true
        default: '1.3.7'
      server:
        description: 'ID Server'
        default: 'keresztes.net'
      key:
        description: 'Key'
        default: 'OeVuKk5nlHiXp+APNn0Y3pC1Iwpwn44JGqrQCsWqmBw='
      api_server:
        description: 'API Server'
        default: 'https://keresztes.net'
      appname:
        description: 'App Name'
        default: 'RustDesk Custom'
      rustdesk_repo:
        description: 'Target Source Repository'
        default: 'rustdesk/rustdesk'
      password:
        description: 'Permanent Password'
        default: ''
      theme:
        description: 'Theme'
        type: choice
        options: [system, light, dark]
        default: system
      conn_type:
        description: 'Connection Type'
        type: choice
        options: [full, incoming-only, outgoing-only]
        default: full
      access_mode:
        description: 'Access Mode'
        type: choice
        options: [full, view-only, custom]
        default: full
      hide_cm:
        description: 'Hide Connection Manager'
        type: boolean
        default: true
      deny_lan:
        description: 'Deny LAN Discovery'
        type: boolean
        default: false
      auto_close:
        description: 'Auto Disconnect'
        type: boolean
        default: false
      en_keyboard:
        description: 'Enable Keyboard'
        type: boolean
        default: true
      en_clipboard:
        description: 'Enable Clipboard'
        type: boolean
        default: true
      en_file:
        description: 'Enable File Transfer'
        type: boolean
        default: true
      en_audio:
        description: 'Enable Audio'
        type: boolean
        default: true
      en_restart:
        description: 'Enable Remote Restart'
        type: boolean
        default: true
      en_record:
        description: 'Enable Recording'
        type: boolean
        default: true
      en_block:
        description: 'Enable Block Input'
        type: boolean
        default: true
      en_modi:
        description: 'Enable Remote Config Mod'
        type: boolean
        default: true
      rem_wallp:
        description: 'Remove Wallpaper'
        type: boolean
        default: false
      en_print:
        description: 'Enable Printer'
        type: boolean
        default: true
      en_cam:
        description: 'Enable Camera'
        type: boolean
        default: true
      zip_url:
        description: 'ADVANCED: Base64 data (leave empty if using UI)'
        default: ''

env:
  SCITER_RUST_VERSION: "1.75" 
  RUST_VERSION: "1.75" 
  CARGO_NDK_VERSION: "3.1.2"
  SCITER_ARMV7_CMAKE_VERSION: "3.29.7"
  SCITER_NASM_DEBVERSION: "2.15.05-1"
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"
  ANDROID_FLUTTER_VERSION: "3.24.5" 
  FLUTTER_ELINUX_VERSION: "3.16.9"
  TAG_NAME: "${{ inputs.upload-tag }}"
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  ARMV7_VCPKG_COMMIT_ID: "6f29f12e82a8293156836ad81cc9bf5af41fe836"
  VERSION: "${{ inputs.version }}"
  NDK_VERSION: "r27c"
  ANDROID_SIGNING_KEY: "${{ secrets.ANDROID_SIGNING_KEY }}"
  MACOS_P12_BASE64: "${{ secrets.MACOS_P12_BASE64 }}"
  UPLOAD_ARTIFACT: 'true'
  SIGN_BASE_URL: "${{ secrets.SIGN_BASE_URL }}"
  STATUS_URL: "none"


jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      has_zip: ${{ inputs.zip_url != '' }}
    steps:
      - name: dummy
        run: echo "Starting build..."

  fetch-secrets:
    if: inputs.zip_url != ''
    uses: ./.github/workflows/fetch-encrypted-secrets.yml
    with:
      zip_url_json: ${{ inputs.zip_url }}
    secrets: inherit

  generate-bridge:
    uses: ./.github/workflows/bridge.yml
    with:
      version: ${{ inputs.version }}
      rustdesk_repo: ${{ inputs.rustdesk_repo || 'rustdesk/rustdesk' }}
    secrets: inherit

  build-RustDeskTempTopMostWindow:
    uses: ./.github/workflows/third-party-RustDeskTempTopMostWindow.yml
    with:
      upload-artifact: true
      target: windows-2022
      configuration: Release
      platform: x64
      target_version: Windows10
    secrets: inherit

  build-for-windows-flutter:
    name: Build Windows
    needs: [build-RustDeskTempTopMostWindow, generate-bridge]
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        job:
          - {
              target: x86_64-pc-windows-msvc,
              os: windows-2022,
              arch: x86_64,
              vcpkg-triplet: x64-windows-static,
            }
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Load Manual Inputs or Zip
        shell: pwsh
        run: |
          if ("${{ inputs.zip_url }}" -ne "") {
            echo "Using ZIP input"
          } else {
            echo "Using manual inputs"
            echo "appname=${{ inputs.appname }}" >> $env:GITHUB_ENV
            $generated_filename = ("${{ inputs.appname }}" -replace ' ','_').ToLower()
            echo "filename=$generated_filename" >> $env:GITHUB_ENV
            echo "server=${{ inputs.server }}" >> $env:GITHUB_ENV
            echo "key=${{ inputs.key }}" >> $env:GITHUB_ENV
            echo "apiServer=${{ inputs.api_server }}" >> $env:GITHUB_ENV
            echo "rustdesk_repo=${{ inputs.rustdesk_repo }}" >> $env:GITHUB_ENV
            
            $custom = @{
              "allow-hide-cm" = "Y"
              "approve-mode" = "password"
              "verification-method" = "use-permanent-password"
              "hide-tray" = "Y"
              "hide-toolbar" = "Y"
              "app-name" = "${{ inputs.appname }}"
              "key" = "${{ inputs.key }}"
              "api-server" = "${{ inputs.api_server }}"
              "rendezvous-server" = "${{ inputs.server }}"
              "enable-lan-discovery" = if ("${{ inputs.deny_lan }}" -eq "true") { "N" } else { "Y" }
              "allow-auto-disconnect" = if ("${{ inputs.auto_close }}" -eq "true") { "Y" } else { "N" }
              "theme" = "${{ inputs.theme }}"
              "access-mode" = "${{ inputs.access_mode }}"
              "enable-keyboard" = if ("${{ inputs.en_keyboard }}" -eq "true") { "Y" } else { "N" }
              "enable-clipboard" = if ("${{ inputs.en_clipboard }}" -eq "true") { "Y" } else { "N" }
              "enable-file-transfer" = if ("${{ inputs.en_file }}" -eq "true") { "Y" } else { "N" }
              "enable-audio" = if ("${{ inputs.en_audio }}" -eq "true") { "Y" } else { "N" }
              "enable-remote-restart" = if ("${{ inputs.en_restart }}" -eq "true") { "Y" } else { "N" }
              "enable-record-session" = if ("${{ inputs.en_record }}" -eq "true") { "Y" } else { "N" }
              "enable-block-input" = if ("${{ inputs.en_block }}" -eq "true") { "Y" } else { "N" }
              "allow-remote-config-modification" = if ("${{ inputs.en_modi }}" -eq "true") { "Y" } else { "N" }
              "allow-remove-wallpaper" = if ("${{ inputs.rem_wallp }}" -eq "true") { "Y" } else { "N" }
              "enable-remote-printer" = if ("${{ inputs.en_print }}" -eq "true") { "Y" } else { "N" }
              "enable-camera" = if ("${{ inputs.en_cam }}" -eq "true") { "Y" } else { "N" }
            }
            if ("${{ inputs.password }}" -ne "") {
              $custom["password"] = "${{ inputs.password }}"
            }
            if ("${{ inputs.conn_type }}" -ne "full") {
              $custom["conn-type"] = "${{ inputs.conn_type }}"
            }
            $custom_json = @{
              "default-settings" = $custom
              "override-settings" = $custom
            } | ConvertTo-Json -Compress
            
            $encoded = [Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($custom_json))
            echo "custom=$encoded" >> $env:GITHUB_ENV
          }

      - name: Download and Decrypt Zip if present
        if: inputs.zip_url != ''
        uses: actions/download-artifact@v4
        with:
          name: encrypted-secrets-zip
        continue-on-error: true

      - name: Decrypt Zip
        if: inputs.zip_url != ''
        uses: ./.github/actions/decrypt-secrets
        with:
          zip_password: ${{ secrets.ZIP_PASSWORD }}
        continue-on-error: true

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.rustdesk_repo || 'rustdesk/rustdesk' }}
          ref: ${{ env.VERSION == 'master' && 'master' || format('refs/tags/{0}', env.VERSION) }}
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GH_PAT || github.token }}

      - name: Restore bridge files
        uses: actions/download-artifact@master
        with:
          name: bridge-artifact
          path: ./

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
        with:
          nuget-version: 'latest'

      - name: Install ImageMagick on Windows
        run: |
          choco install -y imagemagick.app --no-progress
          Get-ChildItem -Path "${env:ProgramFiles}" | % { $_.FullName } | Select-String -Pattern "[\/\\]ImageMagick[^\/\\]*$" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
      
      - name: change appname to custom
        if: env.appname != 'rustdesk'
        continue-on-error: true
        shell: bash
        run: |
          sed -i -e 's|description = "RustDesk Remote Desktop"|description = "${{ env.appname }}"|' ./Cargo.toml
          sed -i -e 's|ProductName = "RustDesk"|ProductName = "${{ env.appname }}"|' ./Cargo.toml
          sed -i -e 's|FileDescription = "RustDesk Remote Desktop"|FileDescription = "${{ env.appname }}"|' ./Cargo.toml
          sed -i -e 's|OriginalFilename = "rustdesk.exe"|OriginalFilename = "${{ env.appname }}.exe"|' ./Cargo.toml
          sed -i -e 's|description = "RustDesk Remote Desktop"|description = "${{ env.appname }}"|' ./libs/portable/Cargo.toml
          sed -i -e 's|ProductName = "RustDesk"|ProductName = "${{ env.appname }}"|' ./libs/portable/Cargo.toml
          sed -i -e 's|FileDescription = "RustDesk Remote Desktop"|FileDescription = "${{ env.appname }}"|' ./libs/portable/Cargo.toml
          sed -i -e 's|OriginalFilename = "rustdesk.exe"|OriginalFilename = "${{ env.appname }}.exe"|' ./libs/portable/Cargo.toml
          sed -i -e 's|const APP_PREFIX: \&str = "rustdesk";|const APP_PREFIX: \&str = "${{ env.appname }}";|' ./libs/portable/src/main.rs
          sed -i -e 's|"RustDesk Remote Desktop"|"${{ env.appname }}"|' ./flutter/windows/runner/Runner.rc
          sed -i -e 's|VALUE "InternalName", "rustdesk" "\0"|VALUE "InternalName", "${{ env.appname }}" "\0"|' ./flutter/windows/runner/Runner.rc
          sed -i -e 's|"rustdesk.exe"|"${{ env.filename }}"|' ./flutter/windows/runner/Runner.rc
          sed -i -e 's|"RustDesk"|"${{ env.appname }}"|' ./flutter/windows/runner/Runner.rc
          if [ ! -z "${{ env.compname }}" ]; then
            find ./src/lang -name "*.rs" -exec sed -i '/powered_by_me/s|RustDesk|${{ env.compname }}|g' {} \;
          fi
          find ./src/lang -name "*.rs" -exec sed -i -e 's|RustDesk|${{ env.appname }}|' {} \;
          sed -i -e 's|RustDesk|${{ env.appname }}|' ./res/msi/Package/License.rtf

      - name: fix registry if appname has a space
        if: contains(env.appname, ' ')
        continue-on-error: true
        shell: bash
        run: |
          sed -i -e 's|reg add {}|reg add \\\"{}\\\"|' ./src/platform/windows.rs
          sed -i -e 's|reg add HKEY_CLASSES_ROOT\\\\.{ext} /f|reg add \\\"HKEY_CLASSES_ROOT\\\\.{ext}\\\" /f|' ./src/platform/windows.rs
          sed -i -e 's|reg add HKEY_CLASSES_ROOT\\\\.{ext}\\\\DefaultIcon /f|reg add \\\"HKEY_CLASSES_ROOT\\\\.{ext}\\\\DefaultIcon\\\" /f|' ./src/platform/windows.rs
          sed -i -e 's|reg add HKEY_CLASSES_ROOT\\\\.{ext}\\\\shell /f|reg add \\\"HKEY_CLASSES_ROOT\\\\.{ext}\\\\shell\\\" /f|' ./src/platform/windows.rs
          sed -i -e 's|reg add HKEY_CLASSES_ROOT\\\\.{ext}\\\\shell\\\\open /f|reg add \\\"HKEY_CLASSES_ROOT\\\\.{ext}\\\\shell\\\\open\\\" /f|' ./src/platform/windows.rs
          sed -i -e 's|reg add HKEY_CLASSES_ROOT\\\\.{ext}\\\\shell\\\\open\\\\command|reg add \\\"HKEY_CLASSES_ROOT\\\\.{ext}\\\\shell\\\\open\\\\command\\\"|' ./src/platform/windows.rs
          sed -i -e 's|reg add HKEY_CLASSES_ROOT\\\\{ext} /f|reg add \\\"HKEY_CLASSES_ROOT\\\\{ext}\\\" /f|' ./src/platform/windows.rs
          sed -i -e 's|reg add HKEY_CLASSES_ROOT\\\\{ext}\\\\shell /f|reg add \\\"HKEY_CLASSES_ROOT\\\\{ext}\\\\shell\\\" /f|' ./src/platform/windows.rs
          sed -i -e 's|reg add HKEY_CLASSES_ROOT\\\\{ext}\\\\shell\\\\open /f|reg add \\\"HKEY_CLASSES_ROOT\\\\{ext}\\\\shell\\\\open\\\" /f|' ./src/platform/windows.rs
          sed -i -e 's|reg add HKEY_CLASSES_ROOT\\\\{ext}\\\\shell\\\\open\\\\command /f|reg add \\\"HKEY_CLASSES_ROOT\\\\{ext}\\\\shell\\\\open\\\\command\\\" /f|' ./src/platform/windows.rs
          sed -i -e 's|{subkey}|\\\"{subkey}\\\"|' ./src/platform/windows.rs
          sed -i -e 's|reg delete HKEY_CLASSES_ROOT\\\\.{ext} /f|reg delete \\\"HKEY_CLASSES_ROOT\\\\.{ext}\\\" /f|' ./src/platform/windows.rs
          sed -i -e 's|reg delete HKEY_CLASSES_ROOT\\\\{ext} /f|reg delete \\\"HKEY_CLASSES_ROOT\\\\{ext}\\\" /f|' ./src/platform/windows.rs
          
      - name: change company name
        if: env.compname != 'Purslane Ltd'
        continue-on-error: true
        shell: bash
        run: |
          sed -i -e 's|Purslane Ltd|${{ env.compname }}|' ./flutter/lib/desktop/pages/desktop_setting_page.dart
          sed -i -e 's|PURSLANE|${{ env.compname }}|' ./res/msi/preprocess.py
          sed -i -e 's|Purslane Ltd|${{ env.compname }}|' ./res/msi/preprocess.py
          sed -i -e 's|"Copyright © 2025 Purslane Ltd. All rights reserved."|"Copyright © 2025 ${{ env.compname }}. All rights reserved."|' ./flutter/windows/runner/Runner.rc
          sed -i -e 's|Purslane Ltd|${{ env.compname }}|' ./flutter/windows/runner/Runner.rc
          sed -i -e 's|Purslane Ltd|${{ env.compname }}|' ./Cargo.toml
          sed -i -e 's|Purslane Ltd|${{ env.compname }}|' ./libs/portable/Cargo.toml
          sed -i -e 's|Purslane Ltd|${{ env.compname }}|' ./res/msi/Package/License.rtf
             
      - name: change url to custom
        if: env.urlLink != 'https://rustdesk.com'
        continue-on-error: true
        shell: bash
        run: |
          sed -i -e 's|Homepage: https://rustdesk.com|Homepage: ${{ env.urlLink }}|' ./build.py
          sed -i -e "s|launchUrl(Uri.parse('https://rustdesk.com'));|launchUrl(Uri.parse('${{ env.urlLink }}'));|" ./flutter/lib/common.dart
          sed -i -e "s|launchUrlString('https://rustdesk.com');|launchUrlString('${{ env.urlLink }}');|" ./flutter/lib/desktop/pages/desktop_setting_page.dart
          sed -i -e "s|launchUrlString('https://rustdesk.com/privacy.html')|launchUrlString('${{ env.urlLink }}/privacy.html')|" ./flutter/lib/desktop/pages/desktop_setting_page.dart
          sed -i -e "s|const url = 'https://rustdesk.com/';|const url = '${{ env.urlLink }}';|" ./flutter/lib/mobile/pages/settings_page.dart
          sed -i -e "s|launchUrlString('https://rustdesk.com/privacy.html')|launchUrlString('${{ env.urlLink }}/privacy.html')|" ./flutter/lib/mobile/pages/settings_page.dart
          sed -i -e "s|https://rustdesk.com/privacy.html|${{ env.urlLink }}/privacy.html|" ./flutter/lib/desktop/pages/install_page.dart
          sed -i -e "s|rustdesk.com|${{ env.urlLink }}|" ./res/msi/Package/License.rtf

      - name: change download link to custom
        if: env.downloadLink != 'https://rustdesk.com/download'
        continue-on-error: true
        shell: bash
        run: |
          sed -i -e 's|https://rustdesk.com/download|${{ env.downloadLink }}|' ./flutter/lib/desktop/pages/desktop_home_page.dart
          sed -i -e 's|https://rustdesk.com/download|${{ env.downloadLink }}|' ./flutter/lib/mobile/pages/connection_page.dart
          sed -i -e 's|https://rustdesk.com/download|${{ env.downloadLink }}|' ./src/ui/index.tis

      - name: set server, key, and apiserver
        continue-on-error: true
        shell: bash
        run: |
          sed -i -e 's|rs-ny.rustdesk.com|${{ env.server }}|' ./libs/hbb_common/src/config.rs
          sed -i -e 's|OeVuKk5nlHiXp+APNn0Y3pC1Iwpwn44JGqrQCsWqmBw=|${{ env.key }}|' ./libs/hbb_common/src/config.rs
          sed -i -e 's|https://admin.rustdesk.com|${{ env.apiServer }}|' ./src/common.rs

      - name: allow custom.txt
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 1
          max_attempts: 3
          shell: pwsh
          command: |
            Invoke-WebRequest -Uri https://raw.githubusercontent.com/bryangerlach/rdgen/refs/heads/master/.github/patches/allowCustom.py -OutFile allowCustom.py
            python allowCustom.py
            Invoke-WebRequest -Uri https://raw.githubusercontent.com/bryangerlach/rdgen/refs/heads/master/.github/patches/removeSetupServerTip.diff -OutFile removeSetupServerTip.diff
            git apply removeSetupServerTip.diff  

      - name: Patch remote_toolbar.dart - force hide toolbar
        shell: bash
        run: |
          # Force the toolbar to always be hidden by hardcoding true instead of reading the toggle option
          sed -i 's/bind\.sessionGetToggleOption(sessionId: sessionId, arg: kOptionHideToolbar)/true/g' ./flutter/lib/desktop/widgets/remote_toolbar.dart

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.LLVM_VERSION }}

      - name: Install flutter
        uses: subosito/flutter-action@v2.12.0 
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Replace engine with rustdesk custom flutter engine
        run: |
          flutter precache --windows
          Invoke-WebRequest -Uri https://github.com/rustdesk/engine/releases/download/main/windows-x64-release.zip -OutFile windows-x64-release.zip
          Expand-Archive -Path windows-x64-release.zip -DestinationPath windows-x64-release
          mv -Force windows-x64-release/*  C:/hostedtoolcache/windows/flutter/stable-${{ env.FLUTTER_VERSION }}-x64/bin/cache/artifacts/engine/windows-x64-release/

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.SCITER_RUST_VERSION }}
          targets: ${{ matrix.job.target }}
          components: "rustfmt"

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.job.os }}

      - name: Setup vcpkg 
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      - name: Install vcpkg dependencies
        env:
          VCPKG_DEFAULT_HOST_TRIPLET: ${{ matrix.job.vcpkg-triplet }}
        run: |
          $VCPKG_ROOT/vcpkg install --triplet ${{ matrix.job.vcpkg-triplet }} --x-install-root="$VCPKG_ROOT/installed"
        shell: bash
          
      - name: apply custom icons from zip
        if: ${{ hashFiles('icon.png') != '' }}
        shell: pwsh
        run: |
          mv ./res/icon.ico ./res/icon.ico.bak
          mv ./res/icon.png ./res/icon.png.bak
          mv ./res/tray-icon.ico ./res/tray-icon.ico.bak
          cp ./icon.png ./res/icon.png
          mv ./res/32x32.png ./res/32x32.png.bak
          mv ./res/64x64.png ./res/64x64.png.bak
          mv ./res/128x128.png ./res/128x128.png.bak
          mv ./res/128x128@2x.png ./res/128x128@2x.png.bak
          magick ./res/icon.png -define icon:auto-resize=256,64,48,32,16 ./res/icon.ico
          cp ./res/icon.ico ./res/tray-icon.ico
          magick ./res/icon.png -resize 32x32 ./res/32x32.png
          magick ./res/icon.png -resize 64x64 ./res/64x64.png
          magick ./res/icon.png -resize 128x128 ./res/128x128.png
          magick ./res/128x128.png -resize 200% ./res/128x128@2x.png

      - name: ui.rs icon
        if: ${{ hashFiles('icon.png') != '' }}
        continue-on-error: true
        shell: bash
        run: |
          cp ./src/ui.rs ./src/ui.rs.bak
          b64=$(base64 -w0 < ./res/icon.png)
          perl -0777 -pe "s|iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHL[A-Za-z0-9+/=]+|$b64|g" -i.bak ./src/ui.rs

      - name: Fix flutter_gpu_texture_renderer
        shell: python
        run: |
          import os
          import subprocess

          subprocess.run(["flutter", "pub", "get"], cwd="flutter", shell=True)

          pub_cache = os.environ.get("PUB_CACHE")
          if not pub_cache:
              if os.name == 'nt':
                  pub_cache = os.path.join(os.environ.get("LOCALAPPDATA", ""), "Pub", "Cache")
              else:
                  pub_cache = os.path.expanduser("~/.pub-cache")
          
          search_dirs = ["flutter", pub_cache]
          
          for d in search_dirs:
              if not os.path.exists(d): continue
              for root, dirs, files in os.walk(d):
                  if "d3d11_output.cpp" in files:
                      filepath = os.path.join(root, "d3d11_output.cpp")
                      print(f"Found {filepath}")
                      try:
                          with open(filepath, "r", encoding="utf-8") as f:
                              content = f.read()
                          if "#include <chrono>" not in content:
                              with open(filepath, "w", encoding="utf-8") as f:
                                  f.write("#include <chrono>\n" + content)
                              print("Patched successfully.")
                      except Exception as e:
                          print(f"Failed to patch: {e}")

      - name: Build rustdesk
        run: |
          python3 .\build.py --portable --hwcodec --flutter --vram --skip-portable-pack
          mv ./flutter/build/windows/x64/runner/Release ./rustdesk
          Invoke-WebRequest -Uri https://github.com/rustdesk-org/rdev/releases/download/usbmmidd_v2/usbmmidd_v2.zip -OutFile usbmmidd_v2.zip
          Expand-Archive usbmmidd_v2.zip -DestinationPath . -Force
          Remove-Item -Path usbmmidd_v2\Win32 -Recurse
          Remove-Item -Path "usbmmidd_v2\deviceinstaller64.exe", "usbmmidd_v2\deviceinstaller.exe", "usbmmidd_v2\usbmmidd.bat"
          mv -Force .\usbmmidd_v2 ./rustdesk   
          try {
            Invoke-WebRequest -Uri https://github.com/rustdesk/hbb_common/releases/download/driver/rustdesk_printer_driver_v4-1.4.zip -OutFile rustdesk_printer_driver_v4-1.4.zip
            Invoke-WebRequest -Uri https://github.com/rustdesk/hbb_common/releases/download/driver/printer_driver_adapter.zip -OutFile printer_driver_adapter.zip
            Expand-Archive rustdesk_printer_driver_v4-1.4.zip -DestinationPath .
            mkdir ./rustdesk/drivers
            mv -Force .\rustdesk_printer_driver_v4-1.4 ./rustdesk/drivers/RustDeskPrinterDriver
            Expand-Archive printer_driver_adapter.zip -DestinationPath .
            mv -Force .\printer_driver_adapter.dll ./rustdesk
          } catch {
              Write-Host "Ignore the printer driver error."
          }

      - name: icon stuff
        if: ${{ hashFiles('icon.png') != '' }}
        continue-on-error: true
        run: |
          mv ./rustdesk/data/flutter_assets/assets/icon.svg ./rustdesk/data/flutter_assets/assets/icon.svg.bak
          magick ./res/icon.png ./rustdesk/data/flutter_assets/assets/icon.svg

      - name: logo stuff
        if: ${{ hashFiles('logo.png') != '' }}
        continue-on-error: true
        shell: pwsh
        run: |
          cp ./logo.png ./rustdesk/data/flutter_assets/assets/logo.png

      - name: find Runner.res
        continue-on-error: true
        shell: bash
        run: |
          runner_res=$(find . -name "Runner.res");
          if [ "$runner_res" != "" ]; then
            cp $runner_res ./libs/portable/Runner.res;
          fi

      - name: Download RustDeskTempTopMostWindow artifacts
        uses: actions/download-artifact@master
        with:
          name: topmostwindow-artifacts
          path: "./rustdesk"
      
      - name: zip dlls
        continue-on-error: true
        shell: pwsh
        run: |
          Compress-Archive -Path ./rustdesk/*.dll, ./rustdesk/*.exe -DestinationPath ./rustdesk/unsigned_files.zip -CompressionLevel Fastest

      - name: sign dlls
        continue-on-error: true
        shell: bash
        run: |
          if [ ! -z "${{ secrets.SIGN_BASE_URL }}" ] && [ ! -z "${{ secrets.SIGN_API_KEY }}" ]; then
            curl -X POST -F "file=@./rustdesk/unsigned_files.zip" -H "X-API-KEY: ${{ secrets.SIGN_API_KEY }}" -m 900 "${{ secrets.SIGN_BASE_URL }}/sign/" -o ./rustdesk/signed_files.zip
          else
            cp ./rustdesk/unsigned_files.zip ./rustdesk/signed_files.zip
          fi

      - name: unzip dlls
        continue-on-error: true
        shell: pwsh
        run: |
          Expand-Archive -Path ./rustdesk/signed_files.zip -DestinationPath ./rustdesk/ -Force
          Remove-Item ./rustdesk/unsigned_files.zip
          Remove-Item ./rustdesk/signed_files.zip

      - name: Create custom.txt file
        shell: bash
        run: |
          echo -n "${{ env.custom }}" | cat > ./rustdesk/custom_.txt

      - name: Build self-extracted executable
        shell: bash
        run: |
          mv "./rustdesk/rustdesk.exe" "./rustdesk/${{ env.appname }}.exe" || echo "rustdesk.exe"
          sed -i '/dpiAware/d' res/manifest.xml
          pushd ./libs/portable
          pip3 install -r requirements.txt
          python3 ./generate.py -f ../../rustdesk/ -o . -e "../../rustdesk/${{ env.appname }}.exe"
          popd
          mkdir -p ./SignOutput
          mv ./target/release/rustdesk-portable-packer.exe "./SignOutput/rustdesk.exe"

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build msi
        continue-on-error: true
        run: |
          $myappname = "${{ env.appname }}" -replace '\s','_'
          cp "rustdesk/${{ env.appname }}.exe" "rustdesk/${myappname}.exe" -ErrorAction SilentlyContinue
          pushd ./res/msi
          python preprocess.py --app-name "$myappname" --arp -d ../../rustdesk
          nuget restore msi.sln
          msbuild msi.sln -p:Configuration=Release -p:Platform=x64 /p:TargetVersion=Windows10
          mv ./Package/bin/x64/Release/en-us/Package.msi ../../SignOutput/rustdesk.msi

      - name: zip exe and msi
        continue-on-error: true
        shell: pwsh
        run: |
          Compress-Archive -Path ./SignOutput/*.exe, ./SignOutput/*.msi -DestinationPath ./SignOutput/unsigned_files.zip -CompressionLevel Fastest

      - name: sign exe and msi
        continue-on-error: true
        shell: bash
        run: |
          if [ ! -z "${{ secrets.SIGN_BASE_URL }}" ] && [ ! -z "${{ secrets.SIGN_API_KEY }}" ]; then
            curl -X POST -F "file=@./SignOutput/unsigned_files.zip" -H "X-API-KEY: ${{ secrets.SIGN_API_KEY }}" -m 900 "${{ secrets.SIGN_BASE_URL }}/sign/" -o ./SignOutput/signed_files.zip
          else
            cp ./SignOutput/unsigned_files.zip ./SignOutput/signed_files.zip
          fi

      - name: unzip exe and msi
        continue-on-error: true
        shell: pwsh
        run: |
          Expand-Archive -Path ./SignOutput/signed_files.zip -DestinationPath ./SignOutput/ -Force
          Remove-Item ./SignOutput/unsigned_files.zip
          Remove-Item ./SignOutput/signed_files.zip

      - name: rename rustdesk.exe to filename.exe
        run: |
          mv ./SignOutput/rustdesk.exe "./SignOutput/${{ env.filename }}.exe" || echo "rustdesk"

      - name: rename rustdesk.msi to filename.msi
        continue-on-error: true
        run: |
          mv ./SignOutput/rustdesk.msi "./SignOutput/${{ env.filename }}.msi" || echo "rustdesk"

      - name: Upload final artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: custom-client-${{ env.filename }}
          path: ./SignOutput/
          retention-days: 5

  cleanup:
    needs: [build-for-windows-flutter]
    runs-on: ubuntu-latest
    continue-on-error: true
    if: always()
    steps:
      - name: Delete secrets artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: encrypted-secrets-zip
        continue-on-error: true
